### ISSUE TITLE
挖财无线与前端技术部招聘

### ISSUE THREAD

**Issue by abbshr** [abbshr/abbshr.github.io#66]
### 公司介绍
> 挖财诞生于 2009 年 6 月，于国内率先推出个人记账理财工具，现已发展成为一家涵盖记账、管钱、理财、信用、社区等服务于一体的全方位的互联网财富管理平台，并于 2017 年 5 月获得由国开金融领投 4200 万美元战略投资。

> 详情[点击](http://www.wacai.com/intro/aboutus.jsp)了解~

### 团队介绍
挖财无线和前端团队，目前规模已达百人，在大前端综合领域有广泛的业务应用，覆盖多款线上业务产品。同时有深入技术研究，包括应用性能及用户体验研究、跨平台 RN 技术细粒度更新、Node.js 容器化等方向，团队追求开放、创新、分享的工程师文化，致力于建设国内领先大前端团队~

##### 岗位职责
1. 参与并负责移动端 H5 及 Hybrid 混合开发、React Native 跨平台技术、SPA 单页应用及 NodeJS 全栈中后台等相关产品的系统设计与开发工作；
2. 参与并负责小程序及快应用等相关产品的创新探索；
3. 关注产品用户体验并持续优化，产出可复用组件及框架工具等。

##### 任职条件
1. 对 MVC/MVVM 等模式有一定理解，熟悉 React/Vue/Angular 等主流框架，有实际项目经验
2. 精通 ES6，对前端工程化有一定理解，熟练掌握 Webpack/Git 的使用
3. 熟悉 NodeJS 并具备一定的开发能力
4. 具备良好的代码规范及质量意识，单元测试实践及爱好者
5. 具备良好的团队合作精神和积极主动的沟通意识
6. 具有很强的学习能力和对新技术的追求精神，乐于分享

##### 加分项
- 具有 Hybrid、小程序、跨平台混合开发经验，如 React Native、Weex 等
- 单元测试、持续集成爱好者
- 开源社区有过贡献的优先

### 福利待遇
1. 有竞争的薪酬，全额五险一金，补充医疗保险。
2. 年终奖及年假，体检及每年团队 outing。
3. 丰富团建活动，早饭晚饭及下午茶。

### 工作地点
办公地点杭州、上海两地均可选择:

- 杭州地址：西湖区互联网金融大厦 19 楼，步行可达西湖景区，附近古荡、翠苑等多个小区，租房交通都很便利。
- 上海地址：陆家嘴世纪金融广场三号楼，园区环境优美，交通便捷。

### 联系方式
rankong@wacai.com 内推渠道、方便快捷！

**Comment by billgo** [comment]
霸坑留档，要是能提前搞点个杭州的小姐姐回国工作就投简历😄

**Comment by chuDaxin** [comment]
大神，你们上海地区还招人吗？

**Comment by abbshr** [comment]
@chuDaxin 招
